### ISSUE TITLE
Fix lua being sloooow on crostini

### ISSUE THREAD

**Issue by tapayne88** [tapayne88/dotfiles#84]
Lua seems really slow (especially on start) on crostini. It seems to show multiple sumneko_lua servers starting though this only seems to happen on crostini. I _think_ a combination of that and the limited resources available to crostini is what's causing the issue.

It seems like someone has figured out that it seems to be down to the sumneko_lua version.
https://github.com/folke/lua-dev.nvim/issues/41#issuecomment-1016521091

I should probably downgrade until this is resolved.

**Comment by tapayne88** [comment]
Need to figure out how to pin server version in [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer)

**Comment by cultab** [comment]
Thanks for mentioning this issue in the lua-dev repo, I originally was parsing the server name and version manually. Only after I saw your config I realized that there already is a function for that!

**Comment by tapayne88** [comment]
ah, glad my overzealous ticket linking has been useful for someone! 😄
